version: "3.9"

services:
  yuumi_db:
    image: postgres:15
    container_name: yuumi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: caua1234
      POSTGRES_DB: yuumi
    ports:
      - "5433:5432"
    volumes:
      - yuumi_data:/var/lib/postgresql/data

  yuumi_backend:
    build: .
    container_name: yuumi_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - yuumi_db

volumes:
  yuumi_data:
